import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const desktopRoot = fileURLToPath(new URL("..", import.meta.url));

export const APP_CONFIG_OUTPUT_PATH = resolve(desktopRoot, "src/core/generated-app-config.ts");

/**
 * Build time environment variables that are the app's only source of remote
 * URLs. They are baked into a generated module because the packaged Electron
 * process has no access to the build machine's environment.
 */
export const APP_CONFIG_ENV_KEYS = [
  "SKILLS_MANAGER_BASE_URL",
  "SKILLS_MANAGER_CATALOG_BASE_URL"
] as const;

export type AppConfigEnvKey = (typeof APP_CONFIG_ENV_KEYS)[number];
export type AppConfigValues = Record<AppConfigEnvKey, string>;

/**
 * Trailing slashes are stripped once, here, so every consumer can join paths
 * with a plain template literal and never produce `//v1/catalog`.
 */
const normalizeBaseUrl = (value: string | undefined): string =>
  (value ?? "").trim().replace(/\/+$/, "");

export const readAppConfigValues = (
  env: Record<string, string | undefined> = process.env
): AppConfigValues => ({
  SKILLS_MANAGER_BASE_URL: normalizeBaseUrl(env.SKILLS_MANAGER_BASE_URL),
  SKILLS_MANAGER_CATALOG_BASE_URL: normalizeBaseUrl(env.SKILLS_MANAGER_CATALOG_BASE_URL)
});

export const findMissingAppConfigKeys = (values: AppConfigValues): AppConfigEnvKey[] =>
  APP_CONFIG_ENV_KEYS.filter((key) => !values[key]);

/**
 * A configured value must parse as an absolute https URL. It is also rejected
 * when it contains a control character or exceeds the 2048 character URL limit:
 * - The WHATWG URL parser silently strips control characters (e.g. `\n`) before
 *   parsing, so a check done only after `new URL()` would miss them and bake a
 *   value that looks configured but resolves to the wrong host.
 * - Anything longer than 2048 characters is a misconfiguration, not a real URL.
 * Anything else (missing scheme, a `http://` scheme, a typo like `htpp://`, a
 * `javascript:` URL, or plain garbage) is rejected so it can never be baked
 * into a release build and silently produce a broken installer.
 */
export const isValidAppConfigUrl = (value: string): boolean => {
  if (!value) {
    return false;
  }

  if (/[\u0000-\u001F\u007F]/.test(value)) {
    return false;
  }

  if (value.length > 2048) {
    return false;
  }

  try {
    return new URL(value).protocol === "https:";
  } catch {
    return false;
  }
};

export const findInvalidAppConfigKeys = (values: AppConfigValues): AppConfigEnvKey[] =>
  APP_CONFIG_ENV_KEYS.filter((key) => values[key] !== "" && !isValidAppConfigUrl(values[key]));

/**
 * Canonicalize a validated https URL: lowercases the scheme and host, percent
 * encodes stray characters, then strips the trailing slash the URL parser adds
 * back so consumers can keep joining paths with a plain template literal.
 */
export const canonicalizeAppConfigUrl = (value: string): string => {
  try {
    return new URL(value).href.replace(/\/+$/, "");
  } catch {
    return value;
  }
};

/** Human readable reason a key is rejected, used by the strict mode error. */
const describeAppConfigProblem = (key: AppConfigEnvKey, values: AppConfigValues): string => {
  const value = values[key];

  if (!value) {
    return `  - ${key}: missing or empty`;
  }

  if (/[\u0000-\u001F\u007F]/.test(value)) {
    return `  - ${key}: "${value}" contains a control character`;
  }

  if (value.length > 2048) {
    return `  - ${key}: exceeds the 2048 character limit`;
  }

  let reason: string;
  try {
    const parsed = new URL(value);
    reason = `scheme must be https, found "${parsed.protocol}"`;
  } catch {
    reason = "cannot be parsed as a URL";
  }

  return `  - ${key}: "${value}" is ${reason}`;
};

/**
 * Strict mode turns a missing variable into a build failure. `CI=false` and
 * `CI=0` must not count as "running in CI", so the flag is compared by value
 * rather than by truthiness.
 */
export const isStrictMode = (
  env: Record<string, string | undefined> = process.env,
  argv: string[] = process.argv.slice(2)
): boolean => {
  if (argv.includes("--strict")) {
    return true;
  }

  const ci = (env.CI ?? "").trim().toLowerCase();

  return ci !== "" && ci !== "false" && ci !== "0";
};

export const renderAppConfigModule = (values: AppConfigValues): string =>
  [
    "// 自动生成，勿手改。",
    "// Generated by apps/desktop/scripts/generate-app-config.ts before every build.",
    "//",
    "// Values come from the build environment and are already trimmed with trailing",
    '// slashes removed. An empty string means "not configured": the app then reports',
    "// a configuration error at runtime instead of silently using a stale host.",
    "",
    ...APP_CONFIG_ENV_KEYS.map((key) => `export const ${key} = ${JSON.stringify(values[key])};`),
    ""
  ].join("\n");

const writeIfChanged = (filePath: string, content: string): void => {
  if (existsSync(filePath) && readFileSync(filePath, "utf8") === content) {
    return;
  }

  writeFileSync(filePath, content, "utf8");
};

export const generateAppConfig = (
  env: Record<string, string | undefined> = process.env,
  argv: string[] = process.argv.slice(2)
): number => {
  const values = readAppConfigValues(env);
  const missingKeys = findMissingAppConfigKeys(values);
  const invalidKeys = findInvalidAppConfigKeys(values);
  const problems = [...missingKeys, ...invalidKeys];

  if (problems.length > 0) {
    if (isStrictMode(env, argv)) {
      console.error(
        [
          "generate-app-config: invalid build configuration:",
          ...problems.map((key) => describeAppConfigProblem(key, values)),
          "",
          "Set these environment variables to valid https URLs before building",
          "(GitHub Actions: jobs.build.env, sourced from repository vars), then run the build again."
        ].join("\n")
      );

      return 1;
    }

    // Non-strict (local dev): missing or malformed values become empty strings
    // so the runtime hits the existing configuration-error path instead of
    // shipping a value that looks configured but cannot be opened.
    for (const key of problems) {
      const why = values[key] ? "not a valid https URL" : "missing";
      console.warn(
        `generate-app-config: ${key} (${why}) is ignored; ` +
          "the app will report a configuration error at runtime."
      );
      values[key] = "";
    }
  }

  // Canonicalize valid values (lowercase scheme/host, stable encoding, trailing
  // slash already stripped) so the baked constant is normalized. Empty strings
  // mean "not configured" and are left untouched. Invalid values were already
  // blanked above in non-strict mode, so they skip this step.
  for (const key of APP_CONFIG_ENV_KEYS) {
    if (values[key]) {
      values[key] = canonicalizeAppConfigUrl(values[key]);
    }
  }

  writeIfChanged(APP_CONFIG_OUTPUT_PATH, renderAppConfigModule(values));

  return 0;
};

const entryPoint = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";

if (import.meta.url === entryPoint) {
  process.exitCode = generateAppConfig();
}
