// 自动生成，勿手改。
// Generated by apps/desktop/scripts/generate-app-config.ts before every build.
//
// Values come from the build environment and are already trimmed with trailing
// slashes removed. An empty string means "not configured": the app then reports
// a configuration error at runtime instead of silently using a stale host.

export const SKILLS_MANAGER_BASE_URL = "";
export const SKILLS_MANAGER_CATALOG_BASE_URL = "";
