/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpGithubTokenRouteImport } from './routes/help.github-token'
import { Route as ApiReleasesLatestRouteImport } from './routes/api/releases/latest'

const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpGithubTokenRoute = HelpGithubTokenRouteImport.update({
  id: '/help/github-token',
  path: '/help/github-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasesLatestRoute = ApiReleasesLatestRouteImport.update({
  id: '/api/releases/latest',
  path: '/api/releases/latest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/help/github-token': typeof HelpGithubTokenRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/help/github-token': typeof HelpGithubTokenRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/help/github-token': typeof HelpGithubTokenRoute
  '/api/releases/latest': typeof ApiReleasesLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment-success'
    | '/help/github-token'
    | '/api/releases/latest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/payment-success' | '/help/github-token' | '/api/releases/latest'
  id:
    | '__root__'
    | '/'
    | '/payment-success'
    | '/help/github-token'
    | '/api/releases/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  HelpGithubTokenRoute: typeof HelpGithubTokenRoute
  ApiReleasesLatestRoute: typeof ApiReleasesLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/github-token': {
      id: '/help/github-token'
      path: '/help/github-token'
      fullPath: '/help/github-token'
      preLoaderRoute: typeof HelpGithubTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/releases/latest': {
      id: '/api/releases/latest'
      path: '/api/releases/latest'
      fullPath: '/api/releases/latest'
      preLoaderRoute: typeof ApiReleasesLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  HelpGithubTokenRoute: HelpGithubTokenRoute,
  ApiReleasesLatestRoute: ApiReleasesLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
