/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ab3aeec02282bd7326e045b90a1f2308)
interface __BaseEnv_Env {
	RELEASE_MANIFEST: KVNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
