/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 35f92cdc1734454561c29ca4adb75da6)
interface __BaseEnv_Env {
	SKILLS_MANAGER_RELEASE_MANIFEST: KVNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
