/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ed6f65ff1e31c5ec9c7a0f9026b793b1)
interface __BaseEnv_Env {
	SKILLS_MANAGER_RELEASE_MANIFEST: KVNamespace;
	RESEND_FROM: "Skills Manager <noreply@magicfuture.app>";
	RESEND_API_KEY: "";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEND_FROM" | "RESEND_API_KEY">> {}
}
